# Generated by Django 4.2.20 on 2025-07-07 13:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(default='default', max_length=191, unique=True)),
                ('mot_de_passe', models.CharField(default='default', max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Candidat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('prenom', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=191, unique=True)),
                ('mot_de_passe', models.CharField(default='default', max_length=128)),
                ('date_naissance', models.DateField(blank=True, null=True)),
                ('sexe', models.CharField(choices=[('HOMME', 'Homme'), ('FEMME', 'Femme'), ('AUTRE', 'Autre')], default='AUTRE', max_length=10)),
                ('telephone', models.CharField(blank=True, max_length=20)),
                ('adresse', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'verbose_name': 'Candidat',
                'verbose_name_plural': 'Candidats',
            },
        ),
        migrations.CreateModel(
            name='RH',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('prenom', models.CharField(max_length=50)),
                ('matricule', models.CharField(max_length=50, unique=True)),
                ('email', models.EmailField(max_length=191, unique=True)),
                ('mot_de_passe', models.CharField(max_length=128)),
                ('entreprise_nom', models.CharField(default='ONEE', editable=False, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Offre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('categorie', models.CharField(choices=[('INFORMATIQUE', 'Informatique'), ('MARKETING', 'Marketing'), ('RESSOURCES_HUMAINES', 'Ressources Humaines'), ('FINANCE', 'Finance'), ('AUTRE', 'Autre')], default='AUTRE', max_length=50)),
                ('exigences', models.TextField(blank=True, null=True)),
                ('salaire', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('type_contrat', models.CharField(blank=True, choices=[('CDI', 'CDI'), ('CDD', 'CDD'), ('Stage', 'Stage'), ('Freelance', 'Freelance'), ('Alternance', 'Alternance')], max_length=50, null=True)),
                ('localisation', models.CharField(blank=True, max_length=100, null=True)),
                ('date_publication', models.DateField(auto_now_add=True)),
                ('date_expiration', models.DateField()),
                ('experience_requise', models.CharField(blank=True, max_length=100, null=True)),
                ('niveau_etude', models.CharField(blank=True, help_text='Ex : Bac+3, Bac+5, Master, Doctorat, etc.', max_length=100, null=True)),
                ('rh', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RH.rh')),
            ],
        ),
        migrations.CreateModel(
            name='Candidature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_postulation', models.DateTimeField(auto_now_add=True)),
                ('statut', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('ACCEPTEE', 'Acceptée'), ('REFUSEE', 'Refusée')], default='EN_ATTENTE', max_length=20)),
                ('niveau_etude', models.CharField(choices=[('BAC', 'Baccalauréat'), ('BAC+2', 'Bac +2'), ('BAC+3', 'Bac +3'), ('BAC+5', 'Bac +5'), ('DOCTORAT', 'Doctorat'), ('AUTRE', 'Autre')], default='BAC', max_length=100)),
                ('annee_experience', models.PositiveIntegerField(default=0)),
                ('lettre_de_motivation', models.FileField(blank=True, null=True, upload_to='motivation/')),
                ('cv', models.FileField(blank=True, null=True, upload_to='cvs/')),
                ('cin', models.FileField(blank=True, null=True, upload_to='cin/')),
                ('diplome', models.FileField(blank=True, null=True, upload_to='diplome/')),
                ('permis', models.BooleanField(default=False)),
                ('candidat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RH.candidat')),
                ('offre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RH.offre')),
            ],
        ),
    ]
