# Generated by Django 4.2.20 on 2025-07-07 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RH', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidat',
            name='github_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='candidat',
            name='linkedin_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='candidat',
            name='pays',
            field=models.CharField(blank=True, default='Maroc', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='candidat',
            name='resume_professionnel',
            field=models.TextField(blank=True, help_text='Un court résumé de votre parcours et de vos objectifs', null=True),
        ),
        migrations.AddField(
            model_name='candidat',
            name='titre_profil',
            field=models.CharField(blank=True, help_text='Titre résumant le profil professionnel', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='candidat',
            name='ville',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='offre',
            name='nombre_postes',
            field=models.PositiveIntegerField(default=1, help_text='Nombre de postes disponibles pour cette offre'),
        ),
    ]
