# Generated by Django 4.2.20 on 2025-07-10 14:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RH', '0002_candidat_github_url_candidat_linkedin_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offre',
            name='rh',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='RH.rh'),
        ),
    ]
