# Generated by Django 4.2.20 on 2025-07-10 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RH', '0003_alter_offre_rh'),
    ]

    operations = [
        migrations.AddField(
            model_name='rh',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Employé'), (1, 'Administrateur')], default=0, help_text='0 = employé, 1 = admin'),
        ),
    ]
