# Generated by Django 4.2.20 on 2025-07-16 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RH', '0004_rh_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidature',
            name='statut',
            field=models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('ACCEPTEE', 'Acceptée'), ('concours_Ecrit', 'Concours écrit'), ('concours_Oral', 'Concours oral'), ('REFUSEE', 'Refusée')], default='EN_ATTENTE', max_length=20),
        ),
    ]
