# Generated by Django 4.2.20 on 2025-07-16 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RH', '0005_alter_candidature_statut'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Admin',
        ),
    ]
